### ISSUE TITLE
linked list directory structure

### ISSUE THREAD

**Issue by mkuhlar** [MattUhlar/Interview_Questions#2]
curious why you have a DataStructures/Linked-Lists folder .. but no linked lists under it?  You do have a stack, and a queue .. @MattUhlar

**Comment by MattUhlar** [comment]
The stack and queue were implemented using a linked list. The directory was meant for common interview questions involving linked lists. Im going to add more solutions later, such as reversing a linked list (recursively vs iteratively), insertions, deletions, doubly-linked lists etc..
